### ISSUE TITLE
Component Installation

### ISSUE THREAD

**Issue by advokatb** [PaulAnnekov/home-assistant-padavan-tracker#2]
Hi. Can't figure out where should I put this python file to make it work?

Xiaomi Mi  Mini with Padavan's firmware.
Thanks.

**Comment by PaulAnnekov** [comment]
Check this doc https://developers.home-assistant.io/docs/en/creating_component_loading.html to find the correct path for `custom_components` folder. Keep in mind that `<component name>` = `device_tracker/padavan_tracker.py` in this case.
