### ISSUE TITLE
Padawan tarcker login to rooter

### ISSUE THREAD

**Issue by kenand1970** [PaulAnnekov/home-assistant-padavan-tracker#3]
When I use padawan tracker with home asistant I can not login to rooter admin page.
Message:

Login user IP: 192.168.1.241 (Homme assistan server address)

You cannot Login unless logout another user first.

**Comment by PaulAnnekov** [comment]
Check README https://github.com/PaulAnnekov/home-assistant-padavan-tracker#notes.
