### ISSUE TITLE
Great migration custom component

### ISSUE THREAD

**Issue by acidquest** [PaulAnnekov/home-assistant-padavan-tracker#4]
Hi. Please check compatibility for great migration.
Look this article: https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

**Comment by tiulpin** [comment]
> Hi. Please check compatibility for great migration.
> Look this article: https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

Check out this PR: https://github.com/PaulAnnekov/home-assistant-padavan-tracker/pull/5

**Comment by PaulAnnekov** [comment]
Added via https://github.com/PaulAnnekov/home-assistant-padavan-tracker/pull/6.
