### ISSUE TITLE
Solve the web interface can not log in

### ISSUE THREAD

**Issue by unpack8866** [PaulAnnekov/home-assistant-padavan-tracker#8]
Advanced Settings -> Customization -> Scripts -> Custom User Script -> Run After Router Started，  add to  /usr/sbin/httpd -p 81，alter url: http://192.168.X.X:81/，Can solve the web interface can not log in。

**Comment by PaulAnnekov** [comment]
Added a link to this issue into README. Thanks.

**Comment by Napalmcold** [comment]
Can someone show how the script should look like?

**Comment by Adjenz** [comment]
You add this line:

`/usr/sbin/httpd -p 81 http://192.168.1.1:81/`

**Comment by DimaVins89** [comment]
Спасибо! Помогло
