### ISSUE TITLE
Feature request: post integration in HACS store

### ISSUE THREAD

**Issue by opravdin** [PaulAnnekov/home-assistant-padavan-tracker#9]
HACS store is a pretty easy way to install custom addons in HA. Its not that hard to do it so it will be very cool to see your addon in HACS

**Comment by PaulAnnekov** [comment]
I've added integration with HACS, but I'm still waiting for PR approve to be added to default repo https://github.com/hacs/default/pull/953.

**Comment by PaulAnnekov** [comment]
Now in default HACS repo 🥳  https://github.com/hacs/default/pull/953#issuecomment-860197594
